export const MovieActionTypes = {
  GET_ALL_MOVIES: "GET_ALL_MOVIES",
  GET_SINGLE_MOVIE: "GET_SINGLE_MOVIE",
  FILTER_MOVIE: "FILTER_MOVIE",
  FILTER_RATING: "FILTER_RATING",
  FILTER_YEAR: "FILTER_YEAR",
};
