export const MovieActionTypes = {
  GET_ALL_MOVIES: "GET_ALL_MOVIES",
  GET_SINGLE_MOVIE: "GET_SINGLE_MOVIE",
  FILTER_MOVIE_RATING: "FILTER_MOVIE_RATING",
  SEARCH_MOVIE_NAME: "SEARCH_MOVIE_NAME",
};
